#!/bin/sh
# This script is to set up ubuntu or mint on a fresh install with
# all of my programs. Use the following command on the script so you don't
# need to enter in your password.
# chmod +s debian_install_script

CONFIG_DIRECTORY='./config_files'
PACKAGES_FILE='./packages.txt'

# update repositories
sudo apt-get update -y && sudo apt-get upgrade -y

# install all my packages that I typically start with using a text file that 
# contains the names of all the packages I want to install
[ -f "$PACKAGES_FILE" ] && sudo apt-get install -y $(cat "$PACKAGES_FILE")

### SET UP VIM RELATED THINGS ###
# install vim plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
# need to move .vimrc into the correct spot
cp "$CONFIG_DIRECTORY/.vimrc" "$HOME/"
# open .vimrc and run PlugInstall
vim "$HOME/.vimrc" -c "PlugInstall"

### MOVE FILES INTO THE CORRECT DIRECTORIES ###
# move stardict dictionaries into the right place






